// <auto-generated />
using System;
using LeakDetectionDashboard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeakDetectionDashboard.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("LeakDetectionDashboard.Models.LogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Context")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LogEntries");
                });

            modelBuilder.Entity("LeakDetectionDashboard.Models.Pipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Diameter")
                        .HasColumnType("REAL");

                    b.Property<double>("ExpectedPressureDrop")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("InstallationDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("Length")
                        .HasColumnType("REAL");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PreviousPipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ZoneId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PreviousPipeId");

                    b.HasIndex("ZoneId");

                    b.ToTable("Pipes");
                });

            modelBuilder.Entity("LeakDetectionDashboard.Models.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("DistanceFromPreviousSensor")
                        .HasColumnType("REAL");

                    b.Property<double>("Elevation")
                        .HasColumnType("REAL");

                    b.Property<double>("ExpectedDailyUsage")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsWaterTap")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastCalibrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PreviousSensorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SensorStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PipeId");

                    b.HasIndex("PreviousSensorId");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("LeakDetectionDashboard.Models.SensorSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BreakType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ExpectedUsageMultiplier")
                        .HasColumnType("REAL");

                    b.Property<double>("FlowRate")
                        .HasColumnType("REAL");

                    b.Property<double>("FlowRateVsBaseline")
                        .HasColumnType("REAL");

                    b.Property<int>("Hour")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBreakTime")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLeakPredicted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWorkingHours")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LeakProbability")
                        .HasColumnType("REAL");

                    b.Property<int>("LeakSeverityPredicted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeakTypePredicted")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Minute")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinutesSinceBreakStart")
                        .HasColumnType("INTEGER");

                    b.Property<double>("OccupancyLevel")
                        .HasColumnType("REAL");

                    b.Property<int>("PipeId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PressureCurrent")
                        .HasColumnType("REAL");

                    b.Property<double>("PressureCurrentVsBaseline")
                        .HasColumnType("REAL");

                    b.Property<double>("PressureDropRate")
                        .HasColumnType("REAL");

                    b.Property<double>("PressurePreviousSensor")
                        .HasColumnType("REAL");

                    b.Property<int>("SensorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("WaterUsageDiff")
                        .HasColumnType("REAL");

                    b.Property<int>("ZoneId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SensorId");

                    b.ToTable("SensorSnapshots");
                });

            modelBuilder.Entity("LeakDetectionDashboard.Models.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PollIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PollIntervalMinutes = 5
                        });
                });

            modelBuilder.Entity("LeakDetectionDashboard.Models.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("LeakDetectionDashboard.Models.Pipe", b =>
                {
                    b.HasOne("LeakDetectionDashboard.Models.Pipe", "PreviousPipe")
                        .WithMany()
                        .HasForeignKey("PreviousPipeId");

                    b.HasOne("LeakDetectionDashboard.Models.Zone", "Zone")
                        .WithMany("Pipes")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PreviousPipe");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("LeakDetectionDashboard.Models.Sensor", b =>
                {
                    b.HasOne("LeakDetectionDashboard.Models.Pipe", "Pipe")
                        .WithMany("Sensors")
                        .HasForeignKey("PipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeakDetectionDashboard.Models.Sensor", "PreviousSensor")
                        .WithMany()
                        .HasForeignKey("PreviousSensorId");

                    b.Navigation("Pipe");

                    b.Navigation("PreviousSensor");
                });

            modelBuilder.Entity("LeakDetectionDashboard.Models.SensorSnapshot", b =>
                {
                    b.HasOne("LeakDetectionDashboard.Models.Sensor", "Sensor")
                        .WithMany("Snapshots")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("LeakDetectionDashboard.Models.Pipe", b =>
                {
                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("LeakDetectionDashboard.Models.Sensor", b =>
                {
                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("LeakDetectionDashboard.Models.Zone", b =>
                {
                    b.Navigation("Pipes");
                });
#pragma warning restore 612, 618
        }
    }
}
